name: Delete Workflow & Archive

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        id: workflow
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 7

      - name: Clean Up Archive Packages
        id: archive
        env:
          HOST: "${{ secrets.REMOTE_USER }}@${{ secrets.HOSTHATCH_IP }}"
          REMOTE_PRIVATEKEY: "${{secrets.HOSTHATCH_PRIVATEKEY}}"
        if: env.REMOTE_PRIVATEKEY != null
        run: |
          mkdir -p ~/.ssh/
          install -m 600 /dev/null ~/.ssh/id_rsa
          echo "${{secrets.HOSTHATCH_PRIVATEKEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -q -t -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $HOST \
          bash -c "'cd /data/dnmp/www/openwrt.cc/archive && \
          find . -type d -name releases -mtime +4 | xargs rm -rf && \
          find . -type d -path "*snapshots/packages" -mtime +4 | xargs rm -rf'"
